# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Build sample Java Maven project

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn --batch-mode clean package

  runEchoServer:
    runs-on: macOS-latest
    strategy:
      matrix:
        java: [ 17 ]
    name: Run OSH echo server
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: prepare
        run: |
          brew install yoggy/tap/sendosc
      - name: Test with sendosc
        run: |
          mvn --projects modules/cmds exec:java &
          sleep 120
          echo "send some OSC data ..."
          sendosc 127.0.0.1 5678 /test1 i 123
          sendosc 127.0.0.1 5678 /test2 f 123.45
          sendosc 127.0.0.1 5678 /test3 s teststring
          sendosc 127.0.0.1 5678 /test4 b true
          sendosc 127.0.0.1 5678 /test5 s teststring i 123 f 123.4 b false
          echo "sending is finished"
          sleep 2
          echo
          echo "I'm done here"